services:

  postgres:

    image: postgres:16

    container_name: shiv-ai-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: shiv
      POSTGRES_USER: shiv
      POSTGRES_PASSWORD: shiv

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - shiv-network

  ollama:

    image: ollama/ollama

    container_name: ollama

    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    networks:
      - shiv-network

  backend-service:

    build:
      context: ./backend_service

    container_name: backend-service

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    networks:
      - shiv-network

    extra_hosts:
    - "host.docker.internal:host-gateway"

  local-agent-service:

    build:
      context: ./local_agent_service

    container_name: local-agent-service

    ports:
      - "8005:8005"

    depends_on:
      - ollama

    networks:
      - shiv-network

  # vision-service:

  #   build:
  #     context: ./vision_service

  #   container_name: vision-service

  #   ports:
  #     - "8003:8003"

  #   networks:
  #     - shiv-network

    # devices:
      # - "/dev/video0:/dev/video0"

  # speaker-service:

  #   build:
  #     context: ./speaker_service

  #   container_name: speaker-service

  #   ports:
  #     - "8004:8004"

  #   networks:
  #     - shiv-network

  # audio-service:

  #   build:
  #     context: ./audio_service

  #   container_name: audio-service

  #   ports:
  #     - "8002:8002"

  #   networks:
  #     - shiv-network

volumes:

  postgres_data:

  ollama_data:

networks:

  shiv-network:
    driver: bridge