spring.application.name=backend_service

spring.datasource.url=jdbc:postgresql://shiv-ai-postgres:5432/shiv

spring.datasource.username=shiv

spring.datasource.password=shiv

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true